name: demo one
on:
  push:
    path:
      - '!README.md'
      - '!docs/**'
    branchs:
      - 'main'
      - 'release/**'
      - '!dev/**'
  pull_request:
    type: [opened,reopened,synchronize,labeled,unlabeld]
  workflow_dispatch:
jobs:
  demo-one:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: "do not build"
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo hello world, today is $TODAY
