name: production
on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare SSH
        run: >
          cd ~ && mkdir .ssh &&
          touch ~/.ssh/known_hosts &&
          ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
        env:
          IP: ${{ secrets.REMOTE_HOST }}

      - name: "rsync deployments"
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -ahv --delete --recursive
          path: ./*
          remote_path: /phu/test-cicd
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: root
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_key_pass: ${{ secrets.REMOTE_KEY_PASS }}
